### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by reliable-bam** [Ttl/vna2#3]
First of all, amazing work! I would like to try my hand at cloning this project, and seeing what I can do to increase the frequency range and/or extend to 4 ports. I am in electronics reliability, and often need cheap relatively-accurate RF bench test and in situ (environmental stress) test equipment in the L, S, X, and K bands. Due to business accounting, it's often easier to build engineering boards rather than slug through the arduous capital acquisition steps for equipment that is far more than what I need. My most recent activity requires a stable differential S-par characterization pre/post stress up to 26.5GHz. Obviously I'm not going to get that all in one shot/design/project, and will require an iterative and more complex (and higher part count) solution. This would try to rival the basic capabilities of something like the 5242 4-port PNAs from Keysight/Agilent. If this could be done at 5-10% of the cost, that would be a phenomenal achievement. I would then probably quit my job and make PNA's for a living :-) I think a more reasonable goal would be to target something functional through X band. Any block diagram / recommendations on where to focus for this project would be greatly appreciated. One idea I was thinking about was replacing the baluns with diplexers or filters. This would be much more lossy (particularly in the cross over region) and noisy, but might start me on the path of combining dedicated blocks to handle lower and higher frequency bands without having to source extremely broad band components. As a side note, I'm also aware that calibrating such a beast will be a wholly new project (perhaps a second switched calibration board). I do fully admit that the convenience of Agilent Ecal may be giving me a false impression of how achievable this endevor is.

Also, I had some questions about possible ways to improve performance / noise on your mark-2 VNA design. It seems to me that there is a lot of unused space on the bottom layer. Would it be more efficient to move components that generate noise interference such as receivers/switches to the backside? My thinking is that the internal ground planes should provide some free receiver shielding from the source components and FPGA. Also, this might shorten some of your lines, or place via rows in between some signal lines that are the worst cross-talk offenders (if known). Clearly this would make soldering more of a challenge, but the benefits might outweigh the assy challenges. I was also wondering if you couldn't extend the edge of the board and place the couplers on it? You could pull back the copper grounds for better isolation, and it would cut down on the connectors. The ferrite bead sub assembly is hand solder regardless, and it's one less setup / board fab cost.

Thank you for putting so much effort into making this concept such a successful reality. I'm new to GitHub, and just thrilled that you are sharing the fruits of your labor to perpetuate greater access to advanced analysis tools.

**Comment by Ttl** [comment]
It's usually better to use switches and separate circuits for each band than to try designing one very wideband circuit. I don't think there is any place for a diplexer in VNA since it can be replaced with just a switch because there is only one frequency in the circuit at a time.

I wouldn't put components on the back side. It's hard to solder and doesn't improve isolation that much. Better to use individually shielded compartments or separate PCBs.

Connectors don't cost much and it's cheaper to use separate couplers when they are identical than make one big PCB with multiple copies of couplers.

Also take look at #2 for some other possible improvements.
