### ISSUE TITLE
Coupler BOM do not match photos on the blog

### ISSUE THREAD

**Issue by micovo** [Ttl/vna2#4]
Hi Henrik, 
I'm little confused about the difference between coupler BOM on Github and photos on your blog.
![xcoupler_finished](https://user-images.githubusercontent.com/3930305/35476897-cd150478-03b8-11e8-9811-8b1025f1c616.jpg)
What I see on the photo is 3pcs of 5943000911, 2pcs of 5977000101 and 1pcs of B64290P0687X046.
On the BOM is 2pcs of 5943000911 and 3pcs of 5977000101.
Did You make a change in assembly without posting it on your blog or is it mistake in the BOM?
Thanks, Michal

**Comment by Ttl** [comment]
You're right. I fixed the BOM.

The exact choice of ferrite beads doesn't seem too important. I ran out of some beads and put some different ones in few couplers, but I didn't really notice any significant performance differences.
