### ISSUE TITLE
Cheap shielding

### ISSUE THREAD

**Issue by mordae** [Ttl/vna2#7]
Hi, thanks for sharing!

I have read your articles and hopefully one day I'll be able to replicate your work.

Wouldn't it be possible to implement shielding cheaper than custom milling / bending with the help of 3D printed covers coated with EMI-shielding copper-based spray paint? There are several products specifically for this use and I have seem them claim about 60 dB attenuation for 50 µm coating.

**Comment by reliable-bam** [comment]
Be careful with what you spray over the top of PWBs. Any coating can reduce
switch isolation and introduce coupling. Especially as circuits are in
close proximity.

**Comment by mordae** [comment]
@reliable-bam: I am not sure I follow. I was talking about 3D printing covers (such as those that are usually made from bent metals and soldered on the board - over the components) and coating those. They would have to be mounted using screws instead of being soldered directly, though.
